### ISSUE TITLE
Is there anyway to arbitrarily prevent collapsing / expanding of rows in a tree table?

### ISSUE THREAD

**Issue by csotiriou** [wtmoose/TLIndexPathTools#47]
Is there anyway to arbitrarily prevent collapsing / expanding of rows? I would love to be able to have a callback or a variable of some kind, to indicate that a specific cell cannot be collapsed or expanded.

**Comment by wtmoose** [comment]
What component are you using? There are two extensions that do collapsing.

Tim

**Comment by wtmoose** [comment]
Never mind. From our past conversations, I know you're using the tree controller. I'll add something for this...

**Comment by csotiriou** [comment]
Thank you very much. Yes, I am indeed using the tree controller.

For the time being, I am overriding 

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath

and I am calling "super" only for the nodes I want to have expand / collapse functionality. Although I would personally prefer a more "official" support for this feature

Thank you for the effort you put into this.

**Comment by wtmoose** [comment]
Yes, overriding either `willSelectRowAtIndexPath` or `didSelectRowAtIndexPath` is the way to go.

In addition, I added a `shouldChangeNode` method to `TLTreeTableViewControllerDelegate`. Take a look at version 0.3.9.

**Comment by csotiriou** [comment]
Excellent. It is exactly what I was looking for
