### ISSUE TITLE
TLCollectionViewController with fetchRequest delete NSManagedObject fault crash

### ISSUE THREAD

**Issue by stefreak** [wtmoose/TLIndexPathTools#48]
when using TLCollectionViewController together with an NSFetchRequest and deleting some NSManagedObjects, TLCollectionViewController crashes on performing the updates, because the items in oldDataModel are all faulted and thus always return nil at the identifier key path.

current work around that I am using:

```
#pragma mark - TLIndexPathControllerDelegate

- (void)controller:(TLIndexPathController *)controller didUpdateDataModel:(TLIndexPathUpdates *)updates
{
    // work around a crash involving faults with the identifier when items are deleted
    if (updates.deletedItems.count) {
        [self.collectionView reloadData];
    } else {
        [super controller:controller didUpdateDataModel:updates];
    }
}
```

**Comment by wtmoose** [comment]
Try setting `identifierKeyPath` to `nil`, which will cause TLIPT to use `objectID` as the identifier. You'll need to call `-[NSManagedObjectContext obtainPermanentIDsForObjects]` on any new objects because we can't have `objectID` changing on save.

Does that help?

**Comment by stefreak** [comment]
That helps, thanks.
