### ISSUE TITLE
DataModel+IndexPathUpdates do not detect modified Core Data model objects

### ISSUE THREAD

**Issue by cdzombak** [wtmoose/TLIndexPathTools#51]
I have an app using a `TLCollectionViewController` backed by Core Data and a `TLIndexPathController`. When I modify one of my Core Data objects (in this case, changing its title), the cell isn't updated in the UI.

This is because the item in the `oldDataModel` gets updated transparently by Core Data. So in `-[TLIndexPathUpdates initWithOldDataModel:updatedDataModel:]`:

```objc
            id oldItem = [oldDataModel currentVersionOfItem:item];
            if (oldItem) {
                if (![oldItem isEqual:item]) {
                    [modifiedItems addObject:item];
                }
```

the `[oldItem isEqual:item]` check seems to indicate that the item hasn't been modified, even though in fact it was modified and the old data model has been updated. The old data model is thus out of sync with the UI.

How are changes to Core Data models supposed to be handled?

**Comment by wtmoose** [comment]
`TLIndexPathController` tracks Core Data updates internally and inserts them into the `TLIndexPathUpdates` with this line:

    [updates performSelector:@selector(setModifiedItems:) withObject:self.updatedItems];

So, it should work in theory. Can you dig a little deeper into whats going on with the update tracking in `TLIndexPathController`?

**Comment by cdzombak** [comment]
Ah, ha! So in this case this method is being called as you'd expect on the `TLCollectionViewController`:

```objc
#pragma mark - TLIndexPathControllerDelegate

- (void)controller:(TLIndexPathController *)controller didUpdateDataModel:(TLIndexPathUpdates *)updates
{
    if (!updates.hasChanges) { return; }
    //only perform batch udpates if view is visible
    if (self.isViewLoaded && self.view.window) {
        [updates performBatchUpdatesOnCollectionView:self.collectionView];
    } else {
        [self.collectionView reloadData];
    }
}
```

BUT, `updates.hasChanges` is NO. It seems that calling `setModifiedItems` doesn't set this flag, and in this case I have no other changes in the model.
