### ISSUE TITLE
Realm

### ISSUE THREAD

**Issue by nanoxd** [wtmoose/TLIndexPathTools#53]
First, thanks for making this :confetti_ball:! It has made my job a lot easier. I had a question regarding if this could be used with [Realm](https://realm.io) in place of Core Data?

**Comment by wtmoose** [comment]
I don't know anything about Realm. If you've got a sample table or collection view project that integrate with Realm, I'll take a look and let you know what it would take.

**Comment by nanoxd** [comment]
Sure, I'll get one set up a little later today.

**Comment by nanoxd** [comment]
No longer using Realm so I'll close this out.
