### ISSUE TITLE
Same item in multiple sections: Possible?

### ISSUE THREAD

**Issue by futuretap** [wtmoose/TLIndexPathTools#54]
I have a favorites section on top of the normal list. A favorite item appears in the top favorites section but also in the non-favorites section below. Can I model that using TLIndexPathTools? How? Specifically, I need something like 

    - (NSArray*)indexPathsForItem:(id)item

Items are never moved between those two sections, only added or deleted or moved within a section.

**Comment by wtmoose** [comment]
No, there's no API like that. You can wrap your item in a `TLIndexPathItem` and supply a unique ID for each one. For example, if your item has an `id` field, you could do something like this, creating a unique ID for the favorite item based on the `id` field:

```` Objective-C
NSString *favIdentifier = [NSString stringWithFormat: @"fav-%@", item.identifier]
TLIndexPathItem *favItem = [TLIndexPathItem alloc] initWithIdentifier: favIdentifier sectionName:@"Favorite List" cellIdentifier: nil data:item]];
TLIndexPathItem *item = [TLIndexPathItem alloc] initWithIdentifier:item.id sectionName:@"Normal List" cellIdentifier: nil data:item]];
dataModel = [TLIndexPathDataModel alloc] initWithItems: @[favItem, item]]
````

Then you'd look up index paths by item or by identifier:

```` Objective-C
NSIndexPath *indexPath = [dataModel indexPathForIdentifier: item.identifier]
NSIndexPath *favIndexPath = [dataModel indexPathForIdentifier: favIdentifier]

NSIndexPath *indexPath = [dataModel indexPathForItem: item]
NSIndexPath *favIndexPath = [dataModel indexPathForItem: favItem]
````

Does that do what you need?

p.s. I've got a new block-based cell configuration feature coming to `TLIndexPathItem` this week, which makes them pretty nice to work with.

**Comment by futuretap** [comment]
Thanks, that makes sense.
