### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by alobanov** [wtmoose/TLIndexPathTools#55]
Have you got plans for adding Swift support?

**Comment by wtmoose** [comment]
What did you have in mind?

I'm using TLIPT on multiple a Swift projects.

**Comment by nanoxd** [comment]
Nullability improvements would be very useful

**Comment by wtmoose** [comment]
Added nullability annotations to the core classes:

````
TLIndexPathDataModel
TLIndexPathUpdates
TLIndexPathController
TLIndexPathItem
````

**Comment by nanoxd** [comment]
![](http://i.imgur.com/vG6vSvn.gif)
