### ISSUE TITLE
Warning : Duplicate Item Ignored (Noob Question)

### ISSUE THREAD

**Issue by wm-j-ray** [wtmoose/TLIndexPathTools#57]
Quick and probably stupid question.  I have table row values that are duplicates (think of locations for scenes in a movie script...)  I need to be able to list them all, i.e., two or more scenes can occur in the same location.

Question:  How can I eliminate the above warning (or do I have to fabricate a unique identifier for each row?  Can't I just render them in cells, dupes an all)

Brilliant code by the way...
Thanx for sharing this

**Comment by wtmoose** [comment]
Being able to track data items across data model versions in order to calculate batch updates is a core feature of the library. So, yes, you’ve got to have a unique ID for each row.

**Comment by wm-j-ray** [comment]
Got it. Thanks.
