### ISSUE TITLE
Swift Implementation Question

### ISSUE THREAD

**Issue by wm-j-ray** [wtmoose/TLIndexPathTools#60]
I'm trying to use TLIndexPathTools in a Swift project and am having a hard time init'ing a TLIndexPathDataModel.  

Here is an 'item' of an array of items I'm trying to add:

    public struct StoryBeat  {
       public var title: String = ""
       public var abstract: String=""
       public var summary: String=""
       public var isMajorTurn:Bool = false
       public var act: Int = 1
       public var beatNumber: Int = 0
       public var targetPercentage: Int = 0
       public var plotPoint: Int = 0
    
    public init () {
    }
}

And in another class I have defined an array of the above structs.

     public var beats = [StoryBeat]()

This class is instantiated and the beats are populated using a JSON file.  No problems so far.  I get my Swift array of StoryBeat objects properly instantiated with the JSON data.

Now I want to pass this stuff from my view model into my viewController with a TLIndexPathDataModel as a property on the viewModel.  This is where I get the error.  I'm using this to try to init the TLIndexPathDataModel:

            self.items = StoryStructure().beats
            self.dataModel = TLIndexPathDataModel.init(items:items)

It looks like TLIndexPathDataModel.init, obviously looking for an NSArray of items, and swift doesn't like it.  I get the following failing error on the build:

    'Cannot invoke 'TLIndexPathDataModel.Type.init' with an argument list of type '(items: (StoryBeat))'

I'm a rookie at Swift, so I'm probably missing something, but I'd love to be able to figure it out.  TLIndexPath is killer in objC and I want to use it going forward in Swift.

Any help is greatly appreciated.

**Comment by wtmoose** [comment]
TLIPT is an Objective-C framework, which means that it doesn't understand Swift structs. You've got to put an array of `NSObjects` into the data model. If you need to use structs, the current best solution is to define a subclass of NSObject that holds your struct on a property.

**Comment by wm-j-ray** [comment]
OK, I moved from struct to class : NSObject and it looks the model is getting populated.  So mutability and references it is I guess.

Thanx of the help and for getting back at blistering speed.

PS.  Got any Swift examples you feel like throwing up there in your examples folder?
