### ISSUE TITLE
Crash when reordering items

### ISSUE THREAD

**Issue by urazov-s** [wtmoose/TLIndexPathTools#62]
Example project: https://github.com/urazov-s/tableTest
Steps to reproduce:
1. Tap Fill button.
2. Tap Switch button

**Comment by wtmoose** [comment]
Thanks or reporting this. I've implemented a fix, but I've been too busy to do proper testing. Stay tuned.

**Comment by wtmoose** [comment]
Fixed in version 0.4.2
