### ISSUE TITLE
Unable to get dynamic height working

### ISSUE THREAD

**Issue by sumowesley** [wtmoose/TLIndexPathTools#64]
I have to say it works fine in the example app but I'm unable to get it to resize a cell when put into my own environment. Feels like I'm missing something obvious and I've brought it back to a single label to get that working first.

Xcode 7.2.1, target of IOS 9.2.

I've checked:
- Label has Lines=0 and Line breaks=Word Wrap
- Cell is set to the right class
- Cell says it will use the <TLDynamicSizeView> protocol
- Constraints for label seem to pin it in to the superview in all four directions

Differences:
- You have explicit width for the label. Made no difference when I set a width.
- You are using Plain tableview - made no difference when I changed mine over
- I'm pushing my view controller through a navigationController - made no difference when I showed it modally.

Suggestions welcome.

**Comment by wtmoose** [comment]
TLIPT's self sizing cell method will only work if you view controller is a subclass of `TLTableViewController` and you're not overriding `heightForRowAtIndexPath`.

But now that Apple supports self sizing cells, I recommend using their method. In my experience it is easier to use.

1. Remove the TLDynamicSizeView protocol from your cell.
2. Implement `estimatedHeightForRowAtIndexPath` in your table view controller and return some reasonable value.
3. `TLTableViewController's` implementation of `heightForRowAtIndexPath` should return `UITableViewAutomaticDimension` if you are using a universal storyboard. But if you find that it doesn't, you'll also want to implement `heightForRowAtIndexPath` and return `UITableViewAutomaticDimension`.

If it still doesn't work, you most likely have an issue with your Auto Layout constraints and I'd need to take a look at them to give you a better answer.

**Comment by sumowesley** [comment]
View controller is definitely a subclass of the TLTableViewController and I'm not overriding any of the sizing delegate methods.

I had already tried setting `tableView.estimatedRowHeight` in viewDidLoad and set the `tableView.rowHeight` to `UITableViewAutomaticDimension` in there as well. I had not implemented `heightForRowAtIndexPath` or `estimateHeightForRowAtIndexPath` elsewhere though.

I will give them a go.

**Comment by sumowesley** [comment]
Outstanding - that works.

Many thanks.

**Comment by wtmoose** [comment]
Cool!
